default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("ACTIVE_RECORD_CONNECTION_POOL") { 20 } %>
  connect_timeout: 5
  variables:
    statement_timeout: 15s
    lock_timeout: 10s

development:
  <<: *default
  host: db-tardis-user
  port: 5433
  user: tardis-user
  database: tardis-user

production:
  <<: *default
  database: tardis-user

test:
  <<: *default
  database: raketa_test
  pool: 1

production:
  <<: *default
  database: tardis-user
