default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("ACTIVE_RECORD_CONNECTION_POOL") { 20 } %>
  connect_timeout: 5
  host: tardis-postgres
  user: tardis-user
  variables:
    statement_timeout: 15s
    lock_timeout: 10s

development:
  <<: *default
  host: tardis-postgres
  port: 5432
  user: tardis-user
  database: tardis-user

production:
  <<: *default
  database: tardis-user

test:
  <<: *default
  host: tardis-postgres
  user: tardis-user
  database: tardis-user-test
  pool: 1
